[
  {
    id: 1,
    code: "3530",
    name: "PLACA FECH. P/ PORTA CORRER",
    category: "Metais",
    image: "assets/Untitled_design-removebg-preview.png.webp",
  },
  {
    id: 2,
    code: "3532",
    name: "PLACA FECH. P/ JANELA",
    category: "Metais",
    image: "assets/Untitled_design-removebg-preview.png.webp",
  },
  {
    id: 3,
    code: "3534",
    name: "CONTRA FECH. P/ 3530",
    category: "Metais",
    image: "assets/Untitled_design-removebg-preview-1.png.webp",
  },
  {
    id: 4,
    code: "3536",
    name: "CONTRA FECH. P/ 3532",
    category: "Metais",
    image: "assets/Untitled_design-removebg-preview-1.png.webp",
  },
  {
    id: 5,
    code: "3210 (1520X)",
    name: "PLACA FECH. CENTRAL S/ PUXADOR",
    category: "Metais",
    image: "assets/Untitled_design__1_-removebg-preview.png.webp",
  },
  {
    id: 6,
    code: "3211",
    name: "CONTRA FECH. C/ ABA P/ 3210",
    category: "Metais",
    image: "assets/Untitled_design__3_-removebg-preview.png.webp",
  },
  {
    id: 7,
    code: "3230",
    name: "ESPELHO INJETADO REFORÇADO",
    category: "Metais",
    image: "assets/Untitled_design__2_-removebg-preview.png.webp",
  },
  {
    id: 8,
    code: "3212",
    name: "CONTRA FECH. S/ ABA P/ 3210",
    category: "Metais",
    image: "assets/Untitled_design__2_-removebg-preview-1.png.webp",
  },
  {
    id: 9,
    code: "1520",
    name: "PLACA INJETADA C/ PARAFUSOS EMBUTIDOS",
    category: "Metais",
    image: "assets/Untitled_design__4_-removebg-preview.png.webp",
  },
  {
    id: 10,
    code: "1504-A",
    name: "ESPELHO EM ALUM. COM BATENTE P/1520 INJETADO REFORÇADO",
    category: "Metais",
    image: "assets/Untitled_design__5_-removebg-preview.png.webp",
  },
  {
    id: 11,
    code: "1531",
    name: "CONTRA FECH. COM BATENTE P/1520",
    category: "Metais",
    image: "assets/Untitled_design__6_-removebg-preview.png.webp",
  },
  {
    id: 12,
    code: "1101",
    name: "DOBRADIÇA PIVOTANTE SUPERIOR REFORÇADA",
    category: "Metais",
    image: "assets/Untitled_design__8_-removebg-preview.png.webp",
  },
  {
    id: 13,
    code: "1102",
    name: "DOBRADIÇA PIVOTANTE INFERIOR REFORÇADA",
    category: "Metais",
    image: "assets/Untitled_design__8_-removebg-preview.png.webp",
  },
  {
    id: 14,
    code: "1009 (1201A)",
    name: "PIVO P/ 1101, 1230 E 1231",
    category: "Metais",
    image: "assets/Untitled_design__10_-removebg-preview.png.webp",
  },
  {
    id: 15,
    code: "1014",
    name: "PIVO P/ 1102",
    category: "Metais",
    image: "assets/Untitled_design__11_-removebg-preview.png.webp",
  },
  {
    id: 16,
    code: "1504-TA",
    name: "CONTRA FECH. V/V P/ 1520TA",
    category: "Metais",
    image: "assets/Untitled_design__12_-removebg-preview.png.webp",
  },
  {
    id: 17,
    code: "N/A",
    name: "CONJUNTO DOBRADIÇA PIVOTANTE",
    category: "Metais",
    image: "assets/Untitled_design-removebg-preview-2.png.webp",
  },
  {
    id: 18,
    code: "FECHADURA 1520TA",
    name: "Placa, Maçaneta, Miolo Hela e Espelho",
    category: "Metais",
    image: "assets/Untitled_design__13_-removebg-preview.png.webp",
  },
  {
    id: 19,
    code: "1520TR",
    name: "PLACA FECH. CENTRAL S/ MIOLO P/ TRINCO ROLETE",
    category: "Metais",
    image: "assets/Untitled_design__4_-removebg-preview.png.webp",
  },
  {
    id: 20,
    code: "1531TR",
    name: "CONTRA FECH. C/ BATENTE P/1520TR",
    category: "Metais",
    image: "assets/Untitled_design__6_-removebg-preview.png.webp",
  },
  {
    id: 21,
    code: "1504-A/TR",
    name: "ESPELHO EM ALUM. COM BATENTE P/1520TR",
    category: "Metais",
    image: "assets/Untitled_design__1_-removebg-preview-1.png.webp",
  },
  {
    id: 22,
    code: "N/A",
    name: "MIOLO P/ FECH. 1520TR TRINCO ROLETE AROUCA",
    category: "Metais",
    image: "assets/Untitled_design__2_-removebg-preview-2.png.webp",
  },
  {
    id: 23,
    code: "1570",
    name: "BATE FECHA CENTRAL C/ CADEADO OPCIONAL CENTRAL V/V",
    category: "Metais",
    image: "assets/Untitled_design__3_-removebg-preview-1.png.webp",
  },
  {
    id: 24,
    code: "1571",
    name: "BATE FECHA V/A MODELO C",
    category: "Metais",
    image: "assets/Untitled_design__4_-removebg-preview-1.png.webp",
  },
  {
    id: 25,
    code: "KIT01 1520 V/A PADRÃO",
    name: "01 – Fechadura 1520 com, 01 – Espelho em alumínio com batente, 1504A, 01 – Dobradiça superior 1101 com pivô 1009, 01 – Dobradiça inferior 1102 com pivô 1014",
    category: "Metais",
    image: "assets/Untitled_design__15_-removebg-preview.png.webp",
  },
  {
    id: 26,
    code: "KIT01 1520X (3210) V/A",
    name: "01 – Fechadura 1520X (3210) com miolo, 01 – Espelho em alumínio com batente, 3230, 01 – Dobradiça superior 1101 com pivô 1009, 01 – Dobradiça inferior 1102 com pivô 1014",
    category: "Metais",
    image: "assets/Untitled_design__15_-removebg-preview.png.webp",
  },
  {
    id: 27,
    code: "KIT01 1520TA V/A",
    name: "01 – Fechadura 1520TA com maçaneta e máquina (Hela), 01 – Espelho 1504-A/TA, 01 – Dobradiça superior 1101 com pivô 1009, 01 – Dobradiça inferior 1102 com pivô 1014",
    category: "Metais",
    image: "assets/Untitled_design__16_-removebg-preview.png.webp",
  },
  {
    id: 28,
    code: "KIT09 - FECHADURA P/ PORTA V/V",
    name: "01 – Fechadura 3530 com miolo, 01 – Contra fechadura 3534",
    category: "Metais",
    image: "assets/Untitled_design__17_-removebg-preview.png.webp",
  },
  {
    id: 29,
    code: "KIT 10 - FECHADURA P/ PORTA V/A",
    name: "01 – Fechadura 3530 com miolo, 01 – Espelho em Alumínio 3230",
    category: "Metais",
    image: "assets/Untitled_design__18_-removebg-preview.png.webp",
  },
  {
    id: 30,
    code: "KIT 11 - FECHADURA P/ JANELA V/V",
    name: "01 – Fechadura 3532 com Miolo, 01 – Contra fechadura 3536",
    category: "Metais",
    image: "assets/Untitled_design__19_-removebg-preview.png.webp",
  },
  {
    id: 31,
    code: "KIT 12 - FECHADURA P/ JANELA V/A",
    name: "01 – Fechadura 3532 com miolo, 01 – Espelho em alumínio 3230",
    category: "Metais",
    image: "assets/Untitled_design__20_-removebg-preview.png.webp",
  },
  {
    id: 32,
    code: "KIT MAXI-AR V/A HASTE DE 30cm",
    name: "02 – Dobradiças 1132 (1921), 01 – Haste com 30cm, 1587-30, 01 – Conjunto descanso V/A 1587VA ou V/V 1587VV",
    category: "Metais",
    image: "assets/Untitled_design__5_-removebg-preview-1.png.webp",
  },
  {
    id: 33,
    code: "KIT MAXI-AR V/V HASTE DE 30cm",
    name: "02 – Dobradiças 1131, 01 – Haste com 30cm, 1587-30, 01 – Conjunto descanso V/A 1587VA ou V/V 1587VV",
    category: "Metais",
    image: "assets/Untitled_design__5_-removebg-preview-1.png.webp",
  },
  {
    id: 34,
    code: "KIT05 - BOX V/A AUTOMÁTICO",
    name: "02 – Dobradiças automáticas 1114, 01 – Puxador para Box 1629",
    category: "Metais",
    image: "assets/Untitled_design__7_-removebg-preview-1.png.webp",
  },
  {
    id: 35,
    code: "KIT06 - BASCULANTE V/A PADRÃO",
    name: "02 – Dobradiças 1230, 02 – Pivôs superior 1009, 01 – Trinco 1523, 01 – Contra trinco 1801, 01 – Corrente 1003, 02 – Argolas 1003A, 01 – Engate 1000",
    category: "Metais",
    image: "assets/Untitled_design__8_-removebg-preview-1.png.webp",
  },
  {
    id: 36,
    code: "KIT07 - BASCULANTE V/A GRANDE",
    name: "02 – Dobradiças 1231, 02 – Pivôs superior 1009, 01 – Trinco 1523, 01 – Contra trinco 1801, 01 – Corrente 1003, 02 – Argolas 1003A, 01 – Engate 1000",
    category: "Metais",
    image: "assets/Untitled_design__9_-removebg-preview-1.png.webp",
  },
  {
    id: 37,
    code: "1306",
    name: "SUPORTE P/ UNIÃO DE 2 VIDROS C/ MIOLO",
    category: "Metais",
    image: "assets/Untitled_design__10_-removebg-preview-1.png.webp",
  },
  {
    id: 38,
    code: "1130",
    name: "SUPORTE C/ PINO P/ BASC. E PIVOTANTE",
    category: "Metais",
    image: "assets/Untitled_design__11_-removebg-preview-1.png.webp",
  },
  {
    id: 39,
    code: "1231",
    name: "SUPORTE P/ BASC. E PIVOT. C/ PONTO DE GIRO",
    category: "Metais",
    image: "assets/Untitled_design__12_-removebg-preview-1.png.webp",
  },
  {
    id: 40,
    code: "1523",
    name: "TRINCO CENTRAL P/ BASCULANTE",
    category: "Metais",
    image: "assets/Untitled_design__13_-removebg-preview-1.png.webp",
  },
  {
    id: 41,
    code: "1230",
    name: "DOBRADIÇA P/ BASCULANTE",
    category: "Metais",
    image: "assets/Untitled_design__14_-removebg-preview-1.png.webp",
  },
  {
    id: 42,
    code: "1521 (1335)",
    name: "TRINCO CENTRAL",
    category: "Metais",
    image: "assets/Untitled_design__15_-removebg-preview-1.png.webp",
  },
  {
    id: 43,
    code: "1329",
    name: "SUPORTE CENTRAL",
    category: "Metais",
    image: "assets/Untitled_design__16_-removebg-preview-1.png.webp",
  },
  {
    id: 44,
    code: "1519",
    name: "TRINCO INFERIOR SEM NUCLEO",
    category: "Metais",
    image: "assets/Untitled_design__17_-removebg-preview-1.png.webp",
  },
  {
    id: 45,
    code: "1123",
    name: "DOBRADIÇA COM PINO P/ BASCULANTE",
    category: "Metais",
    image: "assets/Untitled_design__18_-removebg-preview-1.png.webp",
  },
  {
    id: 46,
    code: "1702",
    name: "FIXADOR DE PORTA NO RODAPÉ",
    category: "Metais",
    image: "assets/Untitled_design__19_-removebg-preview-1.png.webp",
  },
  {
    id: 47,
    code: "1131",
    name: "DOBRADIÇA MAXI-AR V/V 40mm entre furos",
    category: "Metais",
    image: "assets/Untitled_design__20_-removebg-preview-1.png.webp",
  },
  {
    id: 48,
    code: "1587-30",
    name: "HASTE 30cm",
    category: "Metais",
    image: "assets/Untitled_design__21_-removebg-preview.png.webp",
  },
  {
    id: 49,
    code: "1132 (1921)",
    name: "DOBRADIÇA MAXI-AR V/A 40mm ENTRE FUROS",
    category: "Metais",
    image: "assets/Untitled_design__22_-removebg-preview.png.webp",
  },
  {
    id: 50,
    code: "1587-35",
    name: "HASTE 35cm",
    category: "Metais",
    image: "assets/Untitled_design__21_-removebg-preview.png.webp",
  },
  {
    id: 51,
    code: "1587VV",
    name: "CONJUNTO DESCANSO V/V PARA 1587",
    category: "Metais",
    image: "assets/Untitled_design__23_-removebg-preview.png.webp",
  },
  {
    id: 52,
    code: "1587VA",
    name: "CONJUNTO DESCANSO V/A PARA 1587",
    category: "Metais",
    image: "assets/Untitled_design__24_-removebg-preview.png.webp",
  },
  {
    id: 53,
    code: "1122",
    name: "CARRINHO DUPLO P/ TRILHO 1030 (Até 80kg)",
    category: "Metais",
    image: "assets/Untitled_design__38_-removebg-preview.png.webp",
  },
  {
    id: 54,
    code: "1122M",
    name: "CARRINHO MINI PARA TRILHO 1030",
    category: "Metais",
    image: "assets/Untitled_design__25_-removebg-preview.png.webp",
  },
  {
    id: 55,
    code: "1126AC",
    name: "CARRINHO DUPLO COM ROLDANA CÔNCAVA",
    category: "Metais",
    image: "assets/Untitled_design__26_-removebg-preview.png.webp",
  },
  {
    id: 56,
    code: "1126A",
    name: "CARRINHO DUPLO C/ ROLDANA MEIA CANA",
    category: "Metais",
    image: "assets/Untitled_design__27_-removebg-preview-1.png.webp",
  },
  {
    id: 57,
    code: "1126DCP",
    name: "CARRINHO DUPLO INVERTIDO PARA PISO",
    category: "Metais",
    image: "assets/Untitled_design__28_-removebg-preview.png.webp",
  },
  {
    id: 58,
    code: "1334",
    name: "GRAPA PARA SACADA 50 X 65mm",
    category: "Metais",
    image: "assets/Untitled_design__29_-removebg-preview.png.webp",
  },
  {
    id: 59,
    code: "1114",
    name: "DOBRADIÇA AUTOMÁTICA P/ BOX",
    category: "Metais",
    image: "assets/Untitled_design__30_-removebg-preview.png.webp",
  },
  {
    id: 60,
    code: "1115",
    name: "DOBRADIÇA SIMPLES P/ BOX",
    category: "Metais",
    image: "assets/Untitled_design__31_-removebg-preview.png.webp",
  },
  {
    id: 61,
    code: "1629",
    name: "PUXADOR PARA BOX alumínio 25mm",
    category: "Metais",
    image: "assets/Untitled_design__32_-removebg-preview.png.webp",
  },
  {
    id: 62,
    code: "1650",
    name: "PUXADOR PARA JANELA / VITRINE ALUMÍNIO 25mm",
    category: "Metais",
    image: "assets/Untitled_design__33_-removebg-preview.png.webp",
  },
  {
    id: 63,
    code: "1101G",
    name: "DOBRADIÇA PIVOTANTE SUPERIOR GRANDE",
    category: "Metais",
    image: "assets/Untitled_design__34_-removebg-preview.png.webp",
  },
  {
    id: 64,
    code: "1102G",
    name: "DOBRADIÇA PIVOTANTE INFERIOR GRANDE",
    category: "Metais",
    image: "assets/Untitled_design__35_-removebg-preview.png.webp",
  },
  {
    id: 65,
    code: "1014G",
    name: "PIVO P/ 1102G",
    category: "Metais",
    image: "assets/Untitled_design__36_-removebg-preview.png.webp",
  },
  {
    id: 66,
    code: "1009G",
    name: "PIVO P/ 1101G",
    category: "Metais",
    image: "assets/Untitled_design__37_-removebg-preview.png.webp",
  },
  {
    id: 67,
    code: "N/A",
    name: "MIOLO P/ 3530 PORTA DE CORRER LINGUETA UNIVERSAL",
    category: "Metais",
    image: "assets/Untitled_design__39_-removebg-preview.png.webp",
  },
  {
    id: 68,
    code: "N/A",
    name: "MIOLO P/ 3532 JANELA DE CORRER LINGUETA UNIVERSAL",
    category: "Metais",
    image: "assets/Untitled_design__39_-removebg-preview.png.webp",
  },
  {
    id: 69,
    code: "N/A",
    name: "MIOLO P/ FECH. 1520 PORTA DE GIRO",
    category: "Metais",
    image: "assets/Untitled_design__41_-removebg-preview.png.webp",
  },
  {
    id: 70,
    code: "N/A",
    name: "MIOLO P/ FECH. 1520X (3210) PORTA DE GIRO",
    category: "Metais",
    image: "assets/Untitled_design__42_-removebg-preview.png.webp",
  },
  {
    id: 71,
    code: "N/A",
    name: "TORRE PINÇA 300mm AÇO INOX COLUNA REFORÇADA 40X20MM X 30CM INOX BASE EM INOX REFORÇADA",
    category: "Metais",
    image: "assets/Untitled_design__44_-removebg-preview.png.webp",
  },
  {
    id: 72,
    code: "1710",
    name: "P/ PORTAS DE CORRER EM TRILHO 1030",
    category: "Metais",
    image: "assets/Untitled_design__45_-removebg-preview.png.webp",
  },
  {
    id: 73,
    code: "1710M",
    name: "MINI CONJ MÃO AMIGA P/ PORTAS DE CORRER EM TRILHO 1030",
    category: "Metais",
    image: "assets/Untitled_design__46_-removebg-preview.png.webp",
  },
  {
    id: 74,
    code: "1679",
    name: "PUXADOR TUBULAR H ALUMÍNIO TUBULAR (CORES) 32mm 45x30cm",
    category: "Metais",
    image: "assets/Untitled_design__47_-removebg-preview.png.webp",
  },
  {
    id: 75,
    code: "1679 CR",
    name: "PUXADOR TUBULAR H ALUMÍNIO TUBULAR 32mm 45x30cm",
    category: "Metais",
    image: "assets/Untitled_design__47_-removebg-preview.png.webp",
  },
  {
    id: 76,
    code: "1679B INOX",
    name: "PUXADOR BARRA CHATA AÇO INOX POLIDO 15 X 30mm 45x30cm",
    category: "Metais",
    image: "assets/Untitled_design__49_-removebg-preview.png.webp",
  },
];
